# Generated by Django 4.2 on 2023-12-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_body_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
